# Generated by Django 4.1.6 on 2023-02-19 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_rename_user_movie_added_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="added_by",
            new_name="user",
        ),
    ]
